# Numpy Arrays

#### Numpy is used in various fields. With respect to AI, numpy is used to store the data in an array format. Numpy has built-in efficient algorithms like in np.linalg to perform specific operations efficiently.
#### Numpy works with arrays. An array consists of elements with the same datatype. For example, [1, 2, 3] is an array because all the elements are of same datatype (int). [1, 'a'] is not an array because the elements are not of same datatype

#### To use numpy we have to import it

In [1]:
import numpy as np

#### np is short for numpy and is a common notation.

## Array creation

In [2]:
l = [1, 2, 3]
a1 = np.array(l)
print(a1)
print(type(a1))

[1 2 3]
<class 'numpy.ndarray'>


#### We can use attributes to check things like size, shape, etc

In [3]:
print(a1.size)
print(a1.shape)
print(a1.dtype)

3
(3,)
int64


#### For type(a1), the output is 'numpy.ndarray'. ndarray stands for n-dimensional array. 
#### 1-D Array is a list of numbers.
#### 2-D Array is a list of numbers of m rows and n columns.
#### 3-D Arrays is 2-D Arrays stacked together
#### 4-D Arrays is considered higher dimensional arrays and each element is the N-1 Dimension Array

In [4]:
# 1D Array
a1 = np.array([1, 2, 3])

# 2D Array
a2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3D Array
a3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])


print("a1.ndim =", a1.ndim)
print("a1.shape =", a1.shape)
print()

print("a2.ndim =", a2.ndim)
print("a2.shape =", a2.shape)
print()

print("a3.ndim =", a3.ndim)
print("a3.shape =", a3.shape)

a1.ndim = 1
a1.shape = (3,)

a2.ndim = 2
a2.shape = (2, 3)

a3.ndim = 3
a3.shape = (2, 2, 3)


#### ndim attribute tells the dimension of the array. a2 is a 2D Array and hence a2.ndim outputs 2

## Array Creation
#### There are many ways to create an array
## 1) np.array(list or tuple)
#### This is used to convert list or tuple into an array

In [5]:
l = [1, 2, 3]
a1 = np.array(l)
a1

array([1, 2, 3])

## 2) np.empty(shape), np.empty_like(list or tuple)
#### Both these functions creates an uninitialized array of the given shape. In the case of empty_like() function, it takes the shape of the list or the tuple provided.
#### Since it is uninitialized, it is faster to create an array using this method.

In [6]:
a2 = np.empty([3, 3]) #empty(shape)
a3 = np.empty_like(l)

print(a2)
print(a3)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 5.553e-321]
 [0.000e+000 0.000e+000 0.000e+000]]
[0 0 0]


## 3) identity(integer), eye(integer)
#### identity() is the identity matrix

In [23]:
a4 = np.identity(3)
a5 = np.eye(3)

print(a4)
print()
print(a5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Main difference is we can shift the diagonal in the case of eye() using the parameter 'K'.

In [27]:
a6 = np.eye(4, k=1)
a6

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

## 4) ones(shape or integer), ones_like(list or tuple)
#### ones() creates an array of shape same as the given shape and all the elements are 1.
#### ones_like() creates all elements as 1 and the shape is the shape of the list or tuple

In [29]:
l = [
    [1, 2, 3],
    [4, 5, 6]
]
a7 = np.ones(3)
a8 = np.ones((3, 2))
a9 = np.ones_like(l)

print(a7)
print()
print(a8)
print()
print(a9)

[1. 1. 1.]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[1 1 1]
 [1 1 1]]


## 5) zeros(shape or integer), zeros_like(list or tuple)
#### zeros() creates an array of shape same as the given shape and all the elements are 0.
#### zeros_like() creates all elements as 0 and the shape is the shape of the list or tuple

In [30]:
l = [
    [1, 2, 3],
    [4, 5, 6]
]
a10 = np.zeros(3)
a11 = np.zeros((3, 2))
a12 = np.zeros_like(l)

print(a10)
print()
print(a11)
print()
print(a12)

[0. 0. 0.]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[0 0 0]
 [0 0 0]]


## 6) full(shape or integer, integer or array), full_like(list or tuple, integer or array)
#### The second parameter (integer or array) is called the fill value.
#### full() creates an array of shape same as the given shape and all the elements are the fill value.
#### full_like() creates all elements as 0 and the shape is the shape of the list or tuple.

In [36]:
l = [
    [1, 2, 3],
    [4, 5, 6]
]
a13 = np.full(3, 100)
a14 = np.full((3, 2), [1, 2])
a15 = np.full_like(l, 100)

print(a13)
print()
print(a14)
print()
print(a15)

[100 100 100]

[[1 2]
 [1 2]
 [1 2]]

[[100 100 100]
 [100 100 100]]


## 7) arange(start, stop, step)
#### Creates an array starting from start to stop-1 and evenly spaced.

In [39]:
a16 = np.arange(10)
a17 = np.arange(10, 20)
a18 = np.arange(1, 100, 10)

print(a16)
print()
print(a17)
print()
print(a18)

[0 1 2 3 4 5 6 7 8 9]

[10 11 12 13 14 15 16 17 18 19]

[ 1 11 21 31 41 51 61 71 81 91]



## 7) linspace(start, stop, n)
#### Creates an array starting from start to stop and exactly n numbers such that all the elements are evenly spaces
#### n=50 by default

In [47]:
a19 = np.linspace(1, 10)
a20 = np.linspace(10, 100, 10)
a21 = np.linspace([1, 2], [3, 4], 3)

print(a19)
print()
print(a20)
print()
print(a21)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]

[[1. 2.]
 [2. 3.]
 [3. 4.]]

