## PyTorch is a Machine learning framework where AI models can be implemented and saved for inference.

#### It can be used by importing torch

In [3]:
import torch

#### PyTorch works with tensors. A tensor is a multidimensional array storing the elements with same datatype. To convert to tensor, tensor() function is used.


#### i) Scalar is a 0D array. It stores just the number (the magnitude).
#### To find number of dimensions, ndim attribute is used.

In [5]:
import torch

scalar = torch.tensor(1000000)
print(scalar)
print(scalar.ndim)

tensor(1000000)
0


#### ii) Vector is a 1D Array.

In [10]:
vector = torch.tensor([_ for _ in range(1, 6)])
print(vector)
print(vector.ndim)

tensor([1, 2, 3, 4, 5])
1


#### iii) Matrix is a 2D array.

In [11]:
MATRIX = torch.tensor([[_ for _ in range(1, 6)],
                       [_ for _ in range(6, 11)]])

print(MATRIX)
print(MATRIX.ndim)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
2


#### Anything higher than 2 dimension is considered a tensor.

In [12]:
TENSOR = torch.tensor([[[_ for _ in range(1, 6)],
                        [_ for _ in range(6, 11)]]])

print(TENSOR)
print(TENSOR.ndim)

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]])
3


## torch.rand()

#### While training a model, initially there will be random weights. This is implemented using rand() can be used. It gives the numbers in the range [0, 1].

#### Syntax: TENSOR = torch.rand(shape)

In [13]:
TENSOR = torch.rand(1, 2, 3)

print(TENSOR)
print(TENSOR.ndim)

tensor([[[0.0216, 0.2665, 0.9149],
         [0.6953, 0.7815, 0.2260]]])
3


#### Tensors are the faster when compared to numpy arrays because tensors can natively perform parallel processing using GPU, TPU and other specialized hardwares. Numpy can do multi-core processing but it is limited to CPU.

## Tensor Attributes

#### i) shape
#### It shows the shape of the tensor.

In [9]:
import torch

v = torch.tensor([[[1, 2, 3, 4],
                  [5, 6, 7, 8]]])
print(v.shape)
print(v.ndim)

torch.Size([1, 2, 4])
3


## ii) dtype
#### It tells what type of data is stored in the tensor.
#### Common datatypes are int32, int64, bool, float32, float64

In [10]:
import torch

v = torch.tensor([[[1, 2, 3, 4],
                  [5, 6, 7, 8]]])
print(v.dtype)


torch.int64


## iii) device
#### It tells where the tensor lives (GPU, CPU, TPU, etc)

In [11]:
import torch

v = torch.tensor([[[1, 2, 3, 4],
                  [5, 6, 7, 8]]])
print(v.device)

cpu
