## Tensor operations



## i) Addition
#### Tensors can be added by using the '+' operator. It adds element wise.

In [9]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

c = a + b
print(c)

tensor([5, 7, 9])


## ii) Subtraction
#### Tensors can be subtracted using the '-' operator. It subtracts element wise.

In [10]:
import torch

a = torch.tensor([10, 20, 30])
b = torch.tensor([4, 5, 6])

c = a - b
print(c)

tensor([ 6, 15, 24])


## iii) Scalar Multiplication
#### Tensors can be multiplied by a constant using the '*' operator.

In [11]:
import torch

a = torch.tensor([1, 2, 3])
k = 5

c = k*a
print(c)

tensor([ 5, 10, 15])


## iv) Element wise multiplication
#### Tensors can be multiplied element by element by using the "*" operator. When the "*" operator is used between two tensors, then it performs element wise multiplication

In [13]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

c = a * b
print(c)

tensor([ 4, 10, 18])


## v) matrix multiplication
#### Tensors can be multiplied using the "@" operator.
#### a@b is a shorthand notation for torch.matmul(a, b)

In [21]:
import torch

a = torch.tensor([[1, 2, 3]])
b = torch.tensor([[4],
                  [5], 
                  [6]])

c = a @ b
d = b @ a
e = torch.matmul(a, b)

print("c = ", c)
print("\nd = ", d)
print("\ne = ", e)
print("c == e", c == e)

c =  tensor([[32]])

d =  tensor([[ 4,  8, 12],
        [ 5, 10, 15],
        [ 6, 12, 18]])

e =  tensor([[32]])
c == e tensor([[True]])


#### In the above example, c is the matrix multiplication for the shapes (1, 3) @ (3, 1). Hence, the output size is (1, )
#### Similarly, for d, (3, 1) @ (1, 3). Hence, d has the output size (3, 3)

## vi) Division
#### Division is done using the "/" operator. It is done element by element

#### '/' is used for floating number (exact answer) as output
#### '//' is used for the interger part (quotient) as output

In [ ]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

c = b/a
print(c)

tensor([4, 2, 2])


## vii) Scalar Division
#### All the elements can be divided by a scalar.

In [28]:
import torch

a = torch.tensor([100, 200, 300])
k = torch.tensor(100)

c = a/k
d = a//k

print(c)
print(d)

tensor([1., 2., 3.])
tensor([1, 2, 3])
